# [START settings]
default: &default
  project_id: your-project-id
  pubsub_topic: your-pubsub-topic
  pubsub_subscription: your-pubsub-subscription
# [END settings]
  oauth2:
    client_id: your-client-id
    client_secret: your-client-secret
  cloud_storage:
    bucket: your-bucket-name
    access_key_id: your-access-key-id
    secret_access_key: your-secret-access-key

development:
  <<: *default

production:
  <<: *default
