source "https://rubygems.org"

gem "rails"
gem "jquery-rails"

group :production do
  gem "mysql2" # or pg
end

group :development, :test do
  gem "sqlite3"
end

group :test do
  gem "rspec-rails"
  gem "rack-test"
  gem "capybara"
end
