# Copyright 2015 Google, Inc
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo: false
language: ruby
branches:
  only: [master]
rvm:
- 2.5
- 2.6

cache:
  directories:
  # We cache the SDK so we don't have to download it again on subsequent builds.
  - $HOME/google-cloud-sdk

env:
  global:
  - PATH=$PATH:$HOME/google-cloud-sdk/bin
  - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/credentials.json
  - BUILD_ID=$TRAVIS_BUILD_ID

before_install:
#ENCRYPT YOUR PRIVATE KEY (If you need authentication)
# 1. Install and login to the Travis CLI:
#       $ gem install travis
#       $ travis login
# 2. Move your json private key to credentials.json
# 3. Run:
#       $ travis encrypt-file credentials.json --add
# 4. Commit changes:
#       $ git add credentials.json.enc
#       $ git commit credentials.json.enc .travis.yml
- openssl aes-256-cbc -K $encrypted_990eecf37889_key -iv $encrypted_990eecf37889_iv
  -in credentials.json.enc -out credentials.json -d
- gcloud auth activate-service-account --key-file credentials.json
# Update  to Bundler 2.0
- gem update --system
- gem install bundler

install:
- pushd bookshelf
- bundle install --jobs=3 --retry=3
- bash spec/setup.sh
- popd
- pushd sessions
- bundle install --jobs=3 --retry=3
- popd

script:
- pushd bookshelf
- bundle exec rspec spec --backtrace --format documentation
- popd
- pushd sessions
- bundle exec rake test
- bundle exec rake acceptance
- popd
