default: &default
  dataset_id: [YOUR_PROJECT_ID]

development:
  <<: *default

production:
  <<: *default

# Test configuration
test:
  # Datastore
  dataset_id: gcd-test-dataset-directory
  # SQL
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
