default: &default
  project_id: [YOUR_PROJECT_ID]
  storage_bucket: [YOUR_BUCKET_NAME]
  pubsub_topic: [YOUR_PUBSUB_TOPIC]
  pubsub_subscription: [YOUR_PUBSUB_SUBSCRIPTION]
  oauth2:
    client_id: your-client-id
    client_secret: your-client-secret

development:
  <<: *default

production:
  <<: *default
