source "https://rubygems.org"

gem "gcloud", git: "https://github.com/GoogleCloudPlatform/gcloud-ruby.git"
gem "sinatra"
gem "slim"

group :development do
  gem "shotgun"
end

group :test do
  gem "rspec"
  gem "capybara"
  gem "rack-test"
end
