<<<<<<< HEAD
mysql_settings: &mysql_settings
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: your-mysql-user-here
  password: your-mysql-password-here
  host: your-mysql-IPv4-address-here
  database: your-mysql-database-here

development:
  <<: *mysql_settings

production:
  <<: *mysql_settings

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
=======
development:
  dataset_id: your-project-id

production:
  dataset_id: your-project-id

test:
  # $ gcd.sh create gcd_test_dataset_directory
  # $ gcd.sh start --testing ./gcd_test_dataset_directory/
  dataset_id: gcd_test_dataset_directory
  host: http://localhost:8080/
>>>>>>> 2-cloud-datastore
