postgresql_settings: &postgresql_settings
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: your-postgresql-user-here
  password: your-postgresql-password-here
  host: your-postgresql-IPv4-address-here
  database: your-postgresql-database-here

development:
  <<: *postgresql_settings

production:
  <<: *postgresql_settings

test:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3
