default: &default
  project_id: your-project-id
  gcs_bucket: your-bucket-name
  oauth2:
    client_id: your-client-id
    client_secret: your-client-secret

development:
  <<: *default

production:
  <<: *default
