default: &default
  oauth2:
    client_id: [YOUR_CLIENT_ID]
    client_secret: [YOUR_CLIENT_SECRET]
  cloud_storage:
    bucket: [YOUR_BUCKET_NAME]
    access_key_id: [YOUR_ACCESS_KEY]
    secret_access_key: [YOUR_SECRET]

development:
  <<: *default

production:
  <<: *default
