# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

# [START getting_started_requirements]
gem "sinatra", "~> 2.0"
gem "jwt", "~> 2.2"
# [END getting_started_requirements]
